server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    properties:
      show-sql: true
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: h2
  datasource:
    url: jdbc:h2:file:./PASSWORD_WALLET
    username: sa
    password:
    platform: h2
